### ISSUE TITLE
Label spacing

### ISSUE THREAD

**Issue by claudio-moya** [rakuten-rex/switch#14]
## Stories
- [ ] Add new story to have padding between the switch icon and label, similar way of material ui (suggested solution using Grid)

Something like this
```
<List><Col>{text}</Col><Col><Switch></Col></List>
```
![image](https://user-images.githubusercontent.com/10554673/77512377-45a89200-6eb6-11ea-9bac-efa6a4e50614.png)

**Comment by montomos** [comment]
> * Add new story to have padding between the switch icon and label, similar way of material ui (suggested solution using Grid)

Hi, @claudio-moya,
Added this solution to the branch below. Please take a look at it and leave comment after this.
https://github.com/rakuten-rex/switch/tree/feature/add_new-layout

- Grid Layout only works in SwitchToggle not SwitchToggleGroup.
- Added Label Margin Theme options which you have to set margin in each components adjust to the length of label, so it is inefficient.

**Comment by claudio-moya** [comment]
thanx for the fix
