### ISSUE TITLE
BrowserStack QA

### ISSUE THREAD

**Issue by claudio-moya** [rakuten-rex/switch#8]
## Switch Toggle
- [x] Default
https://rakuten-rex.github.io/switch/iframe.html?id=switch-toggle-controlled--default-view
- [x] Checked
https://rakuten-rex.github.io/switch/iframe.html?id=switch-toggle-controlled--checked-view
- [x] Disabled
https://rakuten-rex.github.io/switch/iframe.html?id=switch-toggle-controlled--disabled-view
- [x] Theme
https://rakuten-rex.github.io/switch/iframe.html?id=switch-toggle-controlled--with-theme-react-and-css-vars

## Switch Toggle Group
- [x] Default
https://rakuten-rex.github.io/switch/iframe.html?id=switch-toggle-group-controlled--default-view
- [x] List
https://rakuten-rex.github.io/switch/iframe.html?id=switch-toggle-group-controlled--with-dynamic-props-group
- [x] Theme
https://rakuten-rex.github.io/switch/iframe.html?id=switch-toggle-group-controlled--with-theme-react-and-css-vars

**Comment by montomos** [comment]
All cases have issues on Windows 10 ie 11 and layout issues on several android devices

**Switch Toggle**
default

checked

disabled

theme

**Switch Toggle Group**
default

list

theme
